# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Applitools Demonstration
email: mail@jeremyjarvis.net
description: >- # this means to ignore newlines until "baseurl:"
  A demonstration of testing an Angular app using Applitools, Cucumber, Protractor, and Chai.
# baseurl: "/applitools-demo" # the subpath of your site, e.g. /blog
# url: "https://vertigon451.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  vertigon451

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "See the example project on Github":
    - "//github.com/vertigon451/applitools-demo"
aux_links_new_tab: true

permalink: pretty
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/vertigon451/applitools-demo"
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


# Exclude from processing.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: [ "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md" ]
